crowdsourcer/models.py, crowdsourcer/static/css/_variables.scss, crowdsourcer/static/css/main.scss, crowdsourcer/templates/crowdsourcer/authority_questions.html
Allows skipping to a specific Q or to the save button.
part of #25
=> Add an internal nav bar to marking page

crowdsourcer/management/commands/import_councils.py, crowdsourcer/management/commands/import_questions.py
=> script to add council users

crowdsourcer/management/commands/import_questions.py
Allows changes to question text without updating scores or options
For #50
=> add update text only option to question import script

crowdsourcer/management/commands/send_council_signup_email.py, templates/registration/council_password_email.html, templates/registration/council_password_email_subject.txt
=> script and templates for sending registration email to councils

crowdsourcer/forms.py, crowdsourcer/tests/test_right_of_reply_views.py, crowdsourcer/views/rightofreply.py
Fix one issue plus add a couple of extra tests for reassurance.
=> Enable blanking ror answers

crowdsourcer/admin.py, crowdsourcer/management/commands/activate_audit_volunteers.py, crowdsourcer/management/commands/assign_remaining_audit_section.py, crowdsourcer/management/commands/import_audit_volunteers.py
=> script to mark audit users as active

crowdsourcer/forms.py
=> Alter 'evidence' wording

crowdsourcer/views/base.py
Apply fix from 'progress' views to 'list' views
=> Apply question_types change to list views

crowdsourcer/templates/crowdsourcer/authority_audit_questions.html
One of the possible answers doesn't apply in this case so add a message to that effect.
=> display message about transport q11 for district councils

crowdsourcer/views/progress.py
=> fix question types for volunteer progress screen

crowdsourcer/management/commands/import_foi_data.py, crowdsourcer/management/commands/import_national_data.py
=> WIP national data import script

crowdsourcer/fixtures/authorities.json, crowdsourcer/management/commands/export_marks.py, crowdsourcer/models.py, crowdsourcer/scoring.py, crowdsourcer/tests/test_export.py, crowdsourcer/views/stats.py
=> Handle country specific questions when marking

crowdsourcer/management/commands/import_national_data.py
Import national data
Fixes #102
=> national data import script

ARCHITECTURE.md, DATA.md, LICENSE.txt, README.md
part of https://github.com/mysociety/caps/issues/615
=> Add some documentation

crowdsourcer/tests/test_views.py, crowdsourcer/views/base.py
Given I've not been able to replicate the underlying issue I've essentially taken a best guess approach to what the problem is based on the evidence and written a fix that should resolve that. It's not totally foolproof in that it assumes that the duplicate submissions are identical but I don't understand how they cannot be.
It doesn't throw up an error, just silently throws away the identical data and carries on which I think is fine as then end result will be the same for the user and this way they don't get an error message they can't do anything about.
Fixes #40
=> attempt to reduce duplicate sumissions and hence responses

crowdsourcer/management/commands/add_missing_markers.py
we need these now for various things and we did not in the past so add them in for users who are missing them.
Fixes #153
=> management command to fill in missing Marker objects

ceuk-marking/settings.py, ceuk-marking/urls.py, crowdsourcer/forms.py, crowdsourcer/templates/crowdsourcer/volunteers/create.html, crowdsourcer/templates/crowdsourcer/volunteers/edit.html, crowdsourcer/templates/crowdsourcer/volunteers/list.html, crowdsourcer/views/volunteers.py, crowdsourcer/volunteers.py
This also adds a page to create a whole new user from scratch as we need to add in the correct marker object which is a two step process in the admin.
Fixes #154
=> Add a "send registration email" button to the user editing pages

.github/workflows/tests.yml, .gitignore, ceuk-marking/settings.py, conf/settings.py-example, crowdsourcer/forms.py, crowdsourcer/static/js/questions.esm.js, crowdsourcer/templates/crowdsourcer/authority_audit_questions.html, crowdsourcer/templates/crowdsourcer/authority_questions.html, crowdsourcer/templates/crowdsourcer/authority_questions_with_previous.html, crowdsourcer/templates/crowdsourcer/authority_ror_questions.html, crowdsourcer/templates/crowdsourcer/includes/skip_questions_dropdown.html, crowdsourcer/tests/test_views.py, crowdsourcer/views/base.py
* Customise labels, help text and which fields are mandatory for forms.
* Make Open/Closed by default for question criteria also configurable.
* Improve display of the skip questions dropdown.
=> Various form changes for WhoFundsThem

ceuk-marking/urls.py, crowdsourcer/templates/crowdsourcer/stats.html, crowdsourcer/tests/test_right_of_reply_views.py, crowdsourcer/views/rightofreply.py, crowdsourcer/views/stats.py
Adds a CSV download of all properties for a session, and also adds them to the Right of Reply CSV download
=> Session properties fixes

crowdsourcer/management/commands/import_2025_gf_q8_audit_responses.py
re-uploads the checked and confirmed version of this data, copying across details from the First Mark where required.
=> upload script for audit answers for Governance & Finance Q8
